.TH "_map" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlocation_map_name\fP [PATH_MAX]"
.br
.ti -1c
.RI "short \fBw\fP"
.br
.ti -1c
.RI "short \fBh\fP"
.br
.ti -1c
.RI "short \fBtexture_c\fP"
.br
.ti -1c
.RI "short \fBentity_c\fP"
.br
.ti -1c
.RI "\fBTEXTURE\fP ** \fBtexture_map\fP"
.br
.ti -1c
.RI "\fBGLOBAL_ENTITY\fP ** \fBentity\fP"
.br
.ti -1c
.RI "\fBGIF_ANIMATION\fP * \fBbackground\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
