.TH "_player" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_player
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "unsigned char \fBstate\fP"
.br
.ti -1c
.RI "unsigned char \fBstate_c\fP"
.br
.ti -1c
.RI "\fBGIF_ANIMATION\fP ** \fBsprites\fP"
.br
.ti -1c
.RI "char \fBregion_map_name\fP [PATH_MAX]"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
