.TH "ENTITY" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ENTITY \- Game local entity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <entity\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBlocal_id\fP"
.br
.ti -1c
.RI "unsigned char \fBstate\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game local entity\&. 


.PP
\fBAuthor\fP
.RS 4
Muly
.RE
.PP
TODO 

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
