.TH "src/entity/entity.h" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/entity/entity.h \- Entity header file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBENTITY\fP"
.br
.RI "Game local entity\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBENTITY\fP * \fBentity_init\fP (short local_id, float x, float y, float w, float h, int flags)"
.br
.ti -1c
.RI "void \fBentity_set_state\fP (\fBENTITY\fP *e, unsigned char state)"
.br
.ti -1c
.RI "void \fBentity_move\fP (\fBENTITY\fP *e, float x, float y)"
.br
.ti -1c
.RI "void \fBentity_destroy\fP (\fBENTITY\fP **e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Entity header file\&. 


.PP
\fBAuthor\fP
.RS 4
Muly
.RE
.PP
TODO 
.SH "Function Documentation"
.PP 
.SS "\fBENTITY\fP * entity_init (short local_id, float x, float y, float w, float h, int flags)"
TODO 
.PP
\fBParameters\fP
.RS 4
\fIlocal_id\fP TODO 
.br
\fIx\fP TODO 
.br
\fIy\fP TODO 
.br
\fIw\fP TODO 
.br
\fIh\fP TODO 
.br
\fIflags\fP TODO 
.RE
.PP
\fBReturns\fP
.RS 4
TODO 
.RE
.PP

.SS "void entity_set_state (\fBENTITY\fP * e, unsigned char state)"
TODO 
.PP
\fBParameters\fP
.RS 4
\fIentity\fP TODO 
.br
\fIstate\fP TODO 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
