.TH "GIF_ANIMATION" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GIF_ANIMATION
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_Texture ** \fBt\fP"
.br
.ti -1c
.RI "int * \fBd\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "unsigned long \fBlen\fP"
.br
.ti -1c
.RI "unsigned long \fBcount\fP"
.br
.ti -1c
.RI "unsigned long \fBtime_start_frame\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
