.TH "xml_parser" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml_parser
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBposition\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
[PRIVATE]
.PP
Parser context 

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
