.TH "xml_document" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml_document
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "   size_t \fBlength\fP"
.br
.ti -1c
.RI "} \fBbuffer\fP"
.br
.ti -1c
.RI "struct \fBxml_node\fP * \fBroot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
[OPAQUE API]
.PP
An \fBxml_document\fP simply contains the root node and the underlying buffer 

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
