.TH "xml_string" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml_string
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t const  * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
[OPAQUE API]
.PP
UTF-8 text 

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
