.TH "xml_node" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml_node
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBxml_string\fP * \fBname\fP"
.br
.ti -1c
.RI "struct \fBxml_string\fP * \fBcontent\fP"
.br
.ti -1c
.RI "struct \fBxml_attribute\fP ** \fBattributes\fP"
.br
.ti -1c
.RI "struct \fBxml_node\fP ** \fBchildren\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
[OPAQUE API]
.PP
An \fBxml_node\fP will always contain a tag name, a 0-terminated list of attributes and a 0-terminated list of children\&. Moreover it may contain text content\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
