.TH "xml_attribute" 3 "G" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml_attribute
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBxml_string\fP * \fBname\fP"
.br
.ti -1c
.RI "struct \fBxml_string\fP * \fBcontent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
[OPAQUE API]
.PP
An \fBxml_attribute\fP may contain text content\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for G from the source code\&.
